
export const metadata = {
    title: "Admin",
    description: "Generated by create next app",
  };
export default function Admin(){
    return (
        <main>
            <h1>Admin</h1>
        </main>
    )
}