import Countmeter from "./components/Countmeter";

export const metadata = {
    title: "Admin",
    description: "Generated by create next app",
  };
export default function Admin(){
    return (
        <main className="p-5">
            <Countmeter/>
        </main>
    )
}