"use client"
import { useTotalDayOrderCount } from "@/lib/firestore/orders/read_count";
import Countmeter from "./components/Countmeter";
import OrderChart from "./components/OrderChart";
import RevenueChart from "./components/RevenueChart";
import { useEffect, useState } from "react";

// export const metadata = {
//     title: "Admin",
//     description: "Generated by create next app",
//   };
export default function Admin(){
    const [dates,setDates]=useState([])
    useEffect(()=>{
        let list=[];
        for(let i=0;i<7;i++){
            const date=new Date();
            date.setDate(date.getDate()-i);
            list.push(date)
        }
        setDates(list)
    },[])
    const {data:items,error,isLoading}=useTotalDayOrderCount({dates:dates})
    if (isLoading) return <div>Loading...</div>;
    if (error) return <div>Error loading data: {error.message}</div>;
    return (
        <main className="p-5 flex  flex-col gap-6">
            <Countmeter/>
            <div className="flex flex-col   gap-4">
                <RevenueChart items={items}/>
                <OrderChart items={items}/>
            </div>
        </main>
    )
}