import { ProductCart } from "@/app/components/Products";
import { algoliasearch } from "algoliasearch";
import SearchBox from "./components/SearchBox";

export const metadata = {
        title: "Search",
        description: "Generated by create next app",
};

const getProducts=async(text)=>{
    if(!text){
        return []
    }
    const client=algoliasearch(
        process.env.NEXT_PUBLIC_ALGOLIA_APP_ID,
        process.env.NEXT_PUBLIC_ALGOLIA_API_KEY,
    )
    const search=await client.searchForHits({
        requests: [
            {
                indexName: "products",
                query: text,
                hitsPerPage: 20, 
            }
        ]
    })
    const hits=search.results[0]?.hits;
    return hits ?? [];
}

export default async function Search ({searchParams}) {
    const {q}=searchParams;
    const products=await getProducts(q);
    return (
        <main className="p-5 min-h-screen flex flex-col gap-3">
            <SearchBox/>
        {products?.length!==0 &&  <div className="w-full flex justify-center">
            <div className="max-w-[900px] flex flex-col gap-5 p-4">
            <h1 className="text-center font-bold text-2xl py-2">Search Result for "{q}"</h1>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 md:gap-5">
            {
                products.map(item=>{
                    return (
                       <ProductCart product={item} key={item?.id}/>
                    )
                })
            }
                </div>
        </div>
        </div>}
        </main>
    )
}