import { getProducts } from "@/lib/firestore/products/read_server";
import Photos from "./components/Photos";
import Details from "./components/Details";
import Reviews from "./components/Reviews";
import RelatedProducts from "./components/RelatedProducts";

export const metadata =  {
  title: "Products",
  description: "Generated by create next app",
}
export default async function Page({ params }) {
  const { productId } = params;
  const product = await getProducts({ id: productId });
  return (
    <main className="p-5 md:p-10  gap-3">
      <section className="flex gap-3 flex-col md:flex-row">
        <Photos imageList={[product?.featureImageURL,...(product?.imageList ?? [])]} />
        <Details product={product} />
      </section>
      <section>
       <Reviews/>
      </section>
      <RelatedProducts categoryId={product?.categoryId} />
    </main>
  );
}
