
import ReviewAdmin from "./components/ReviewAdmin";

export const metadata = {
    title: "Reviews",
    description: "Generated by create next app",
  };
export default function Reviews(){
    return (
        <main className="p-5 flex flex-col gap-3">
            <div className="flex justify-between items-center">
            <h1 className="text-xl">Reviews</h1>
            </div>
            <ReviewAdmin />
        </main>
    )
}