import Favorites from "./favorites";


export const metadata = {
    title: "Favorites",
    description: "Generated by create next app",
}
export default function Page() {
    return (
        <Favorites/>
    )
}