
import CustomerView from "./components/CustomerView";

export const metadata = {
    title: "Customers",
    description: "Generated by create next app",
  };
export default function Customers(){
    return (
        <main className="p-5 flex flex-col gap-3">
            <div className="flex justify-between items-center">
            <h1 className="text-xl">Customers</h1>
            </div>
            <CustomerView />
        </main>
    )
}