
export const metadata = {
    title: "Account",
    description: "Generated by create next app",
}

export default function Account(){
    return (
        <main className="p-5 ">
            <h1>Account</h1>
        </main>
    )
}