import CheckOut from "./checkout"

export const metadata = {
    title: "Checkout",
    description: "Generated by create next app",
}

export default function Page() {
    return(
        <main className="">
            <CheckOut/>
        </main>
    )
}