import React from 'react'
import OrderDetails from './page'

export const metadata = {
    title: 'Order Details',
    description: 'Generated by create next app',
}
export default function layout() {
  return (
    <>
      <OrderDetails/>
    </>
  )
}
